Configuration:
  # describes DSC related settings
  DSC:
    # account used for DSC RunAs operations
    RunAs:
      UserName: "dev\\administrator"
      UserPassword: ""
    # account used SharePoint web app creation process    
    WebPoolManagedAccount:
      UserName: "dev\\administrator"
      UserPassword: ""
    # account used SharePoint web app, site collection and web creation process      
    SPSetupAccount:
      UserName: "dev\\administrator"
      UserPassword: ""
    # VM names to run DSC against
    NodeNames:
      - dev13
      - cloud20
      - cloud21
      - cloud22
      - cloud23
      - cloud24
      - cloud25
      - cloud26
      - cloud27

  # describes regression environment settings
  # SharePoint / SharePoint online web app, site collections and so on
  Environment:
    SharePoint:
      WebApp:
        Port: 31442
        IsHttps: false
      SiteCollection:
        Urls:
          - /
          #- /sites/spmeta2
      Web:
        Urls:
          - /
          #- /sites/spmeta2
    SharePointOnline:
      SiteCollection:
        Urls:
          - https://spmeta2-regression.sharepoint.com
          #- https://spmeta2-regression.sharepoint.com
      Web:
        Urls:
          - https://spmeta2-regression.sharepoint.com
          #- https://spmeta2-regression.sharepoint.com
      UserName: "ci@ci.com"
      UserPassword: ""

  # describes unit tests settings          
  RegressionTests:
    # which tests to run? 
    # SSOM, CSOM - these are run against SharePoint
    # O365 - that's SP2013 CSOM run against SharePoint Online
    # O365v16 - that's SharePoint Online packages run against SharePoint Online
    ObjectModels: 
      - SSOM
      #- CSOM
      #- O365
      #- O365v16
    TestData:
      UserLogins:
      # test user logins to be used with security related tests
      # must not be same account under which tests are run
        - dev\user1
        - dev\user2
      ActiveDirectoryGroups:
      # test group user logins to be used with security related tests
        - dev\group1         
        - dev\group2         
      DomainUserEmails:
        - user1@dev.local
        - user2@dev.local